{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "dnsbl-query.fullname" . }}
  labels:
    app: {{  include "dnsbl-query.fullname" . }}
    chart: {{ include "dnsbl-query.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  {{- if .Values.persistence.hostPath }}
  storageClassName: ""
  {{- end }}
  # TODO: support other storage classes
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end -}}
