// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

// An operation can be used to check the progress of a background task
type Operation struct {
	ID uuid.UUID `json:"id"`
}
