name: Go
on: push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v1
        id: go
        with:
          go-version: 1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go mod download
        env:
          GOPRIVATE: github.com/enmand

      - name: Run tests
        run: go run github.com/magefile/mage -v go:lint
        env:
          GOPRIVATE: github.com/enmand
  test:
    name: Test
    id: false # TODO: enable when there are tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v1
        id: go
        with:
          go-version: 1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go mod download
        env:
          GOPRIVATE: github.com/enmand

      - name: Run tests
        run: go run github.com/magefile/mage -v go:test
        env:
          GOPRIVATE: github.com/enmand

  check_generated:
    name: Check generated files
    runs-on: ubuntu-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v1
        id: go
        with:
          go-version: 1.14

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go mod download
        env:
          GOPRIVATE: github.com/enmand

      - name: Ensure generate files are checked in
        run: go run github.com/magefile/mage -v go:generate && git diff --no-ext-diff --quiet --exit-code
        env:
          GOPRIVATE: github.com/enmand

